apiVersion: apps/v1
kind: Deployment
metadata:
  name: ausf
  namespace: my5gs
  labels:
    app: ausf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ausf
  template:
    metadata:
      labels:
        app: ausf
      annotations:
        ovn.kubernetes.io/ip_address: "172.22.0.11"  # Assign the IP address ovn.kubernetes.io/subnet: "my5gs-subnet"  # Specify the subnet
        ovn.kubernetes.io/logical_switch: "my5gs-subnet"
    spec:
      nodeName: lab-thinkstation-p3-tower
      containers:
        - name: ausf
          image: localhost:5000/docker_open5gs:v1
          env:
            - name: COMPONENT_NAME
              value: ausf-1
          envFrom:
            - configMapRef:
                name: my5gs-config
          volumeMounts:
            - mountPath: /mnt/ausf
              name: ausf-volume
            - mountPath: /open5gs/install/var/log/open5gs
              name: log-volume
            - mountPath: /etc/timezone
              name: timezone
              readOnly: true
            - mountPath: /etc/localtime
              name: localtime
              readOnly: true
      volumes:
        - name: ausf-volume
          hostPath:
            path: /home/lab/k3s/5gs/docker_open5gs/ausf
        - name: log-volume
          hostPath:
            path: /home/lab/k3s/5gs/docker_open5gs/log
        - name: timezone
          hostPath:
            path: /etc/timezone
        - name: localtime
          hostPath:
            path: /etc/localtime

---
apiVersion: v1
kind: Service
metadata:
  name: ausf
  namespace: my5gs
spec:
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
  selector:
    app: ausf
  type: ClusterIP

