apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: my5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
      annotations:
        ovn.kubernetes.io/subnet: my5gs-subnet  # Specify the subnet
        ovn.kubernetes.io/ip_address: "172.22.0.22"  # Replace with your desired IP
    spec:
      nodeName: lab217-thinkcentre-neo-50q-gen-4
      containers:
        - name: grafana
          image: docker_grafana
          envFrom:
            - configMapRef:
                name: my5gs-config  # Ensure this ConfigMap exists in the `my5gs` namespace
          volumeMounts:
            - mountPath: /mnt/grafana
              name: grafana-volume
            - mountPath: /etc/timezone
              name: timezone
              readOnly: true
            - mountPath: /etc/localtime
              name: localtime
              readOnly: true
      volumes:
        - name: grafana-volume
          hostPath:
            path: ./grafana  # Adjust path as necessary
        - name: timezone
          hostPath:
            path: /etc/timezone
        - name: localtime
          hostPath:
            path: /etc/localtime

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: my5gs
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: grafana
  type: ClusterIP

