apiVersion: apps/v1
kind: Deployment
metadata:
  name: nrf
  namespace: my5gs
  labels:
    app: nrf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nrf
  template:
    metadata:
      labels:
        app: nrf
      annotations:
        ovn.kubernetes.io/ip_address: "172.22.0.12" 
        ovn.kubernetes.io/logical_switch: "my5gs-subnet"
    spec:
      nodeName: lab-thinkstation-p3-tower
      containers:
        - name: nrf
          image: localhost:5000/docker_open5gs:v1
          env:
            - name: COMPONENT_NAME
              value: nrf-1
          envFrom:
            - configMapRef:
                name: my5gs-config  # Reference your ConfigMap here
          volumeMounts:
            - mountPath: /mnt/nrf
              name: nrf-volume
            - mountPath: /open5gs/install/var/log/open5gs
              name: log-volume
            - mountPath: /etc/timezone
              name: timezone
              readOnly: true
            - mountPath: /etc/localtime
              name: localtime
              readOnly: true
      volumes:
        - name: nrf-volume
          hostPath:
            path: /home/lab/k3s/5gs/docker_open5gs/nrf  # Adjust path as necessary
        - name: log-volume
          hostPath:
            path: /home/lab/k3s/5gs/docker_open5gs/log  # Adjust path as necessary
        - name: timezone
          hostPath:
            path: /etc/timezone
        - name: localtime
          hostPath:
            path: /etc/localtime

---
apiVersion: v1
kind: Service
metadata:
  name: nrf
  namespace: my5gs
spec:
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
  selector:
    app: nrf
  type: ClusterIP

