apiVersion: apps/v1
kind: Deployment
metadata:
  name: udm
  namespace: my5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udm
  template:
    metadata:
      labels:
        app: udm
      annotations:
        ovn.kubernetes.io/ip_address: "172.22.0.13"  # Replace with your desired IP
        ovn.kubernetes.io/logical_switch: "my5gs-subnet"  # Specify the subnet
    spec:
      nodeName: lab-thinkstation-p3-tower
      containers:
        - name: udm
          image: localhost:5000/docker_open5gs:v1
          env:
            - name: COMPONENT_NAME
              value: udm-1
          envFrom:
            - configMapRef:
                name: my5gs-config  # Ensure this ConfigMap exists in the `my5gs` namespace
          volumeMounts:
            - mountPath: /mnt/udm
              name: udm-volume
            - mountPath: /open5gs/install/var/log/open5gs
              name: log-volume
            - mountPath: /etc/timezone
              name: timezone
              readOnly: true
            - mountPath: /etc/localtime
              name: localtime
              readOnly: true
      volumes:
        - name: udm-volume
          hostPath:
            path: /home/lab/k3s/5gs/docker_open5gs/udm  # Adjust path as necessary
        - name: log-volume
          hostPath:
            path: /home/lab/k3s/5gs/docker_open5gs/log  # Adjust path as necessary
        - name: timezone
          hostPath:
            path: /etc/timezone
        - name: localtime
          hostPath:
            path: /etc/localtime

---
apiVersion: v1
kind: Service
metadata:
  name: udm
  namespace: my5gs
spec:
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
  selector:
    app: udm
  type: ClusterIP

