apiVersion: apps/v1
kind: Deployment
metadata:
  name: du-1
  namespace: my5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: du-1
  template:
    metadata:
      labels:
        app: du-1
      annotations:
        ovn.kubernetes.io/ip_address: 172.22.0.53  # Replace with your desired IP
        ovn.kubernetes.io/logical_switch: "my5gs-subnet"  # Specify the subnet
    spec:
      containers:
        - name: du-1
          image: localhost:5000/srsran-cu:v1
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_NICE", "CAP_SYS_PTRACE"]
          resources:
            requests:
              cpu: "6"
          volumeMounts:
            - mountPath: /dev/bus/usb
              name: usb
            - mountPath: /usr/local/share/uhd/
              name: uhd-images
            - mountPath: /tmp
              name: gnb-storage
            - mountPath: /du_ho_1.yml
              name: du-config
              readOnly: true
          command: ["srsdu", "-c", "du_ho_1.yml"]
          stdin: true
          tty: true
      volumes:
        - name: usb
          hostPath:
            path: /dev/bus/usb
        - name: uhd-images
          hostPath:
            path: /usr/local/share/uhd/
            type: Directory
        - name: gnb-storage
          emptyDir: {}
        - name: du-config
          hostPath:
            path: /home/lab/k3s/5gs/ran/config/du_ho_1.yml
        - name: timezone
          hostPath:
            path: /etc/timezone
        - name: localtime
          hostPath:
            path: /etc/localtime

---
apiVersion: v1
kind: Service
metadata:
  name: du-1
  namespace: my5gs
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: du-1
  type: ClusterIP

